---
abstract: 'Create a DBIx::Class::Schema based on a database'
author:
  - 'Caelum: Rafael Kitover <rkitover@cpan.org>'
build_requires:
  DBD::SQLite: '1.29'
  DBIx::Class::IntrospectableM2M: 0
  ExtUtils::MakeMaker: 6.59
  File::Path: '2.07'
  File::Temp: '0.16'
  Test::Deep: '0.107'
  Test::Differences: '0.60'
  Test::Exception: '0.31'
  Test::More: '0.94'
  Test::Warn: '0.21'
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Schema-Loader
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp::Clan: 0
  Class::Accessor::Grouped: '0.10008'
  Class::C3::Componentised: '1.0008'
  Class::Inspector: '1.27'
  Class::Unload: '0.07'
  DBIx::Class: '0.08127'
  Data::Dump: '1.06'
  Digest::MD5: '2.36'
  Exporter: '5.63'
  Hash::Merge: '0.12'
  Lingua::EN::Inflect::Number: '1.1'
  Lingua::EN::Inflect::Phrase: '0.15'
  Lingua::EN::Tagger: '0.23'
  List::Util: '1.33'
  MRO::Compat: '0.09'
  Scope::Guard: '0.20'
  String::CamelCase: '0.02'
  String::ToIdentifier::EN: '0.05'
  Sub::Util: '1.40'
  Try::Tiny: 0
  namespace::clean: '0.23'
  perl: 5.8.1
resources:
  IRC: irc://irc.perl.org/#dbix-class
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/dbix-class
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dbsrgits/dbix-class-schema-loader
version: '0.07045'
